### PR TITLE
implement: cp

### PR DESCRIPTION
**Pull request by anuragagarwal561994**
The cases being covered here includes:

1. If no argument -> err.
2. If 1 argument -> err.
3. For 2 arguments:
    a. If second argument is not a directory but contains a slash -> err or otherwise will create a new file
    b. If second argument is an already existing file -> overwrite
4. It will always check if all the arguments except the last one is a file, if they are not it will print the correct error message.
5. Last argument for 2 (except for the cases in 3) or more argument has to be a directory or it will report an error or otherwise it will copy the files correctly.

The inspiration of the implementation is taken from the core utilities of GNU.

### CODE REVIEW

**Comment by bpowers** [comment]
(Addresses #13)

**Comment by anuragagarwal561994** [comment]
So well there are still some of the edge cases left which I am going to cover in my next commit.
Right now in case where 2 arguments are given and when the second path does not exist:
1. It can possibly be either an argument not ending in '/' -> to be assumed as file
2. It can be a assumed as a directory when there is a '/' in the end

It is taking both of the paths as file only.

**Comment by bpowers** [comment]
hi @anuragagarwal561994!  The changes you made for `browser-node` look great. It sounds like you have an additional commit in-progress?  If you have any questions, don't hesitate to reach out on there or IRC!

**Comment by bpowers** [comment]
this looks great, merging.  We can add tests as a followup

**Pull request merged**
